-- Trabalho Final Testes               --
-- Autor: Wellington Alexandre da Costa--
-- Professor: Alvaro                   --
-- Banco de Dados LOCADORA             --


-- *********************************** --
--           VIDEO LOCADORA            --          
--          CRIAÇÃO  DATABASE          --
-- *********************************** --

use master;
GO

EXEC XP_CREATE_SUBDIR 'C:\PROGRAMA LOCADORA\BANCO DE DADOS';
GO

CREATE DATABASE [VIDEOLOCADORA]
	ON PRIMARY
	(
		NAME = 'LOCADORA_DATA_1',
		FILENAME = 'C:\PROGRAMA LOCADORA\BANCO DE DADOS\LOCADORA_DATA_1.MDF',
		SIZE = 20MB,
		FILEGROWTH = 10%		
	)
	
	LOG ON
	(
		NAME = 'LOCADORA_LOG',
		FILENAME = 'C:\PROGRAMA LOCADORA\BANCO DE DADOS\LOCADORA_LOG.LDF',
		SIZE = 10 MB,
		FILEGROWTH = 10%	
	);
GO

USE VIDEOLOCADORA
GO

-- *********************************** --
--           CRIAÇÃO  TABELAS          --
-- *********************************** --


CREATE TABLE UF
(
	UF_Cod INT IDENTITY PRIMARY KEY,
	UF_Desc NVARCHAR(3)	
)
GO


CREATE TABLE CIDADES 
(
	CID_Cod INT IDENTITY PRIMARY KEY,
	CID_Desc NVARCHAR(40),
	UF_Cod INT,
	FOREIGN KEY(UF_Cod) REFERENCES UF (UF_Cod)
)
GO

CREATE TABLE ENDERECOS 
(
	END_Cod INT IDENTITY PRIMARY KEY,
	END_Logradouro NVARCHAR(40),
	END_Num NVARCHAR(10),
	END_Complemento NVARCHAR(40),
	END_Bairro NVARCHAR(40),
	END_CEP NVARCHAR(15),
	CID_Cod INT,
	FOREIGN KEY(CID_Cod) REFERENCES CIDADES (CID_Cod)
)
GO

CREATE TABLE CLIENTES 
(
	CLI_COD INT IDENTITY PRIMARY KEY,
	CLI_DATA DATE,
	CLI_NOME NVARCHAR(40),
	CLI_NASC DATE,
	CLI_RG NVARCHAR(15),
	CLI_CPF NVARCHAR(15),
	CLI_SEXO NVARCHAR(2),
	CLI_TEL NVARCHAR(15),
	CLI_CEL NVARCHAR(15),
	CLI_EMAIL NVARCHAR(50),
	CLI_FOTO NVARCHAR(100),
	CLI_SALDO MONEY,
	CLI_STATUS SMALLINT,
	END_COD INT,	
	FOREIGN KEY(END_Cod) REFERENCES ENDERECOS (END_Cod)	
)
GO


CREATE TABLE PARENTESCOS 
(
	PAR_COD SMALLINT IDENTITY PRIMARY KEY,
	PAR_DESC NVARCHAR(10)
)
GO

CREATE TABLE DEPENDENTES 
(
	DEP_COD INT IDENTITY(10000, 1) PRIMARY KEY,
	DEP_NOME NVARCHAR(40),
	DEP_DT_NASC DATE,
	CLI_COD INT,
	PAR_COD SMALLINT,
	FOREIGN KEY(CLI_COD) REFERENCES CLIENTES (CLI_COD),
	FOREIGN KEY(PAR_COD) REFERENCES PARENTESCOS (PAR_COD)
)
GO


-- Tabelas relacionadas aos filmes --


CREATE TABLE GENEROS 
(
	GEN_COD SMALLINT IDENTITY PRIMARY KEY,
	GEN_DESC NVARCHAR(15)
)
GO


CREATE TABLE CATALOGO_PRECOS 
(
	CAT_COD SMALLINT IDENTITY PRIMARY KEY,
	CAT_DESCRICAO NVARCHAR(15),
	VAL_VALOR MONEY
)
GO


CREATE TABLE TIPOS_MIDIAS 
(
	TIP_COD SMALLINT IDENTITY PRIMARY KEY,
	TIP_DESC NVARCHAR(10)
)
GO

CREATE TABLE FILMES 
(
	FIL_COD INT IDENTITY PRIMARY KEY,
	FIL_TITULO NVARCHAR(50),
	GEN_COD SMALLINT,
	FIL_DATA_LANC INT,
	CAT_COD SMALLINT,
	FIL_CLASSIFICACAO INT,
	FIL_DIRETOR NVARCHAR(30),
	FIL_PRODUTORA NVARCHAR(30),
	FIL_SINOPSE NVARCHAR(250),
	FIL_CAPA NVARCHAR(100),
	FOREIGN KEY(GEN_COD) REFERENCES GENEROS (GEN_COD),
	FOREIGN KEY(CAT_COD) REFERENCES CATALOGO_PRECOS (CAT_COD),
	)
GO

CREATE TABLE ATORES 
(
	ATO_COD INT IDENTITY PRIMARY KEY,
	ATO_NOME NVARCHAR(40),
	FIL_COD INT,
	FOREIGN KEY(FIL_COD) REFERENCES FILMES (FIL_COD)
)
GO


CREATE TABLE IDIOMAS 
(
	IDI_COD INT IDENTITY PRIMARY KEY,
	IDI_DESC NVARCHAR(15)
)
GO


CREATE TABLE REL_FIL_IDI 
(
	IDI_COD INT,
	FIL_COD INT,
	FOREIGN KEY(FIL_COD) REFERENCES FILMES (FIL_COD),
	FOREIGN KEY(IDI_COD) REFERENCES IDIOMAS (IDI_COD)	
)
GO

CREATE TABLE CODFILMES
(
	COD_COD INT IDENTITY PRIMARY KEY,
	COD_STATUS SMALLINT,
	FIL_COD INT,
	TIP_COD SMALLINT,
	FOREIGN KEY(FIL_COD) REFERENCES FILMES (FIL_COD),	
	FOREIGN KEY(TIP_COD) REFERENCES TIPOS_MIDIAS (TIP_COD)
)
GO

CREATE TABLE LOCACOES 
(
	LOC_COD INT IDENTITY PRIMARY KEY,
	LOC_DATA_LOC DATE,
	LOC_VALOR MONEY,
	LOC_DATA_DEV DATE,
	LOC_DEP INT,
	LOC_STATUS INT,
	CLI_COD INT,
	COD_COD INT,	
	LOC_DATA_DEVULACAO DATE,
	FOREIGN KEY(CLI_COD) REFERENCES CLIENTES (CLI_COD),
	FOREIGN KEY(COD_COD) REFERENCES CODFILMES (COD_COD)
)

CREATE TABLE USUARIO 
(
	USU_COD INT IDENTITY PRIMARY KEY,
	USU_NOME NVARCHAR(40),
	USU_RG NVARCHAR(15),
	USU_CPF NVARCHAR(15),
	USU_DT_ADIM DATE,
	USU_SEXO VARCHAR(1),
	USU_FOTO NVARCHAR(200),
	USU_LOGIN VARCHAR(20),
	USU_SENHA VARCHAR(60)
)
GO



CREATE TABLE HISTORICO 
(
	HIS_COD INT IDENTITY PRIMARY KEY,
	HIS_DATA DATETIME,
	HIS_OPERACAO SMALLINT,
	HIS_OBJETO INT,
	USU_COD INT,
	FOREIGN KEY(USU_COD) REFERENCES USUARIO (USU_COD)
)
GO


SP_HELP;


-- *********************************** --
--         Populando Tabelas           --
-- *********************************** --


INSERT INTO UF VALUES
	('AC'), ('AL'), ('AP'), ('AM'), ('BA'), ('CE'), ('DF'), ('ES'), ('GO'), ('MA'), ('MT'), ('MS'), ('MG'), ('PA'), ('PB'), ('PR'), ('PE'), ('PI'), ('RJ'), ('RN'), ('RS'), ('RO'), ('RR'), ('SC'), ('SP'), ('SE'), ('TO');
GO

INSERT INTO CIDADES VALUES
	('CAMPOS DO JORDÃO', 25),
	('TAUBATÉ', 25),
	('TREMEMBÉ', 25),
	('SANTO ANTONIO DO PINHAL', 25),
	('PINDAMONHANGABA', 25),
	('CAÇAPAVA', 25),
	('SÃO JOSÉ DOS CAMPOS', 25),
	('JACARÉI', 25),
	('GUARÁ', 25),
	('LORENA', 25),
	('APARECIDA DO NORTE', 25),
	('ITAJUBÁ', 13),
	('BRASÓPOLIS', 13),
	('PARAISÓPOLIS', 13),
	('POUSO ALEGRE', 13);
GO
	


SELECT * FROM CIDADES;
SELECT * FROM UF;

-- Consultas possíveis --

SELECT CIDADES.CID_Desc, UF.UF_Desc FROM UF INNER JOIN CIDADES
ON CIDADES.UF_Cod = UF.UF_Cod
WHERE UF.UF_Desc = 'MG';

SP_HELP ENDERECOS;

INSERT INTO ENDERECOS VALUES
	('R: ANTONIO FURTADO DE SOUSA', '565', '', 'VILA BRITANIA', '12.460-000', 1);
GO

SET DATEFORMAT dmy

INSERT INTO CLIENTES VALUES
	('01-07-2012', 'WELLINGTON ALEXANDRE DA COSTA', '19-04-1993', '49.030.055-8', '417.454.418.24', 'M',
	 '(12)3662-4625', '(12)9140-4582', 'WELL.WADC@GMAIL.COM', '', '0.00', 0, 1);
GO

select*from ENDERECOS

INSERT INTO PARENTESCOS VALUES
	('AMIGA'),
	('AMIGO'),
	('AVÔ'),
	('AVÓ'),
	('CUNHADA'),
	('CUNHADO'),
	('FILHA'),
	('FILHO'),
	('GENRO'),
	('IRMÃ'),
	('IRMÃO'),
	('MARIDO'),
	('MÃE'),
	('MULHER'),
	('NETA'),
	('NETO'),
	('NORA'),
	('PAI'),
	('PRIMA'),
	('PRIMO'),
	('SOGRA'),
	('SOGRO'),
	('TIA'),
	('TIO');
GO


INSERT INTO DEPENDENTES VALUES
	('WESLEY LUCAS DA COSTA', '28-10-1996', 1, 11),
	('EVELIN ALINE DA COSTA', '19-04-1993', 1, 10);
	
SELECT MAX(END_COD) FROM ENDERECOS;

-- *********************************** --
--  Consulta Cliente para pré locação  --
-- *********************************** --


USE VIDEOLOCADORA;

SELECT CLIENTES.CLI_Cod, CLIENTES.CLI_Nome, CLIENTES.CLI_Status 
FROM CLIENTES 
WHERE CLIENTES.CLI_Cod = 1 
UNION 
SELECT DEPENDENTES.DEP_Cod, DEPENDENTES.DEP_Nome, CLIENTES.CLI_Status 
FROM DEPENDENTES inner join CLIENTES 
on DEPENDENTES.CLI_Cod = CLIENTES.CLI_Cod 
WHERE CLIENTES.CLI_Cod = 1;



SELECT CLIENTES.CLI_Cod, CLIENTES.CLI_Nome, CLIENTES.CLI_Status 
FROM CLIENTES 
WHERE CLIENTES.CLI_NOME like'%W%'
UNION 
SELECT DEPENDENTES.DEP_Cod, DEPENDENTES.DEP_Nome, CLIENTES.CLI_Status 
FROM DEPENDENTES inner join CLIENTES 
on DEPENDENTES.CLI_Cod = CLIENTES.CLI_Cod 
WHERE DEPENDENTES.DEP_Nome like'%W%';



SELECT CLIENTES.CLI_Nome, CLIENTES.CLI_Status, CLIENTES.CLI_Data, CLIENTES.CLI_Nasc, CLIENTES.CLI_Saldo, CLIENTES.CLI_Foto from CLIENTES WHERE CLIENTES.CLI_Cod = 1;
SELECT * FROM DEPENDENTES;

-- *********************************** --
--     Populando o base de filmes      --
-- *********************************** --


INSERT INTO GENEROS VALUES
	('AÇÃO'),
	('COMÉDIA'),
	('SUSPENSE'),
	('TERROR'),
	('AVENTURA'),
	('INFANTIL'),
	('ÉPICO'),
	('ROMANCE'),
	('DOCUMEN'),
	('SERIADO'),
	('MUSICAL'),
	('POLICIAL'),
	('FICÇÃO'),
	('ERÓTICO'),
	('GUERRA');
GO


INSERT INTO CATALOGO_PRECOS VALUES
	('LANÇAMENTO', 5.00),
	('NORMAL', 3.50);
GO

INSERT INTO CATALOGO_PRECOS VALUES ('PROMOCIONAL', 0.00)

INSERT TIPOS_MIDIAS VALUES
	('CD'),
	('DVD'),
	('BLU RAY'),
	('FITA');
GO

INSERT INTO FILMES VALUES
('TRÊS DESCULPAS PARA MATAR', 3, 2006, 2, 14, 'JOE GOODMAN', 'SWEN FILMES', '', '')
GO

INSERT INTO IDIOMAS VALUES
	('ALEMÃO'),
	('INGLÊS'),
	('FRANCÊS'),
	('PORTUGUÊS'),
	('JAPONÊS'),
	('ITALIANO'),
	('CHINÊS'),
	('RUSSO');
GO

INSERT INTO REL_FIL_IDI VALUES
	(1, 1)
GO	

	
INSERT INTO CODFILMES VALUES
	(0, 1, 2)
GO	
	
SELECT CODFILMES.COD_Cod, FILMES.FIL_Titulo, GENEROS.GEN_Desc, FILMES.FIL_Classificacao, CATALOGO_PRECOS.CAT_DESCRICAO, TIPOS_MIDIAS.TIP_Desc, CODFILMES.COD_Status 
FROM CODFILMES 
INNER JOIN FILMES
	ON CODFILMES.FIL_Cod = FILMES.FIL_Cod
INNER JOIN GENEROS
	ON FILMES.GEN_Cod = GENEROS.GEN_Cod
INNER JOIN CATALOGO_PRECOS
	ON FILMES.CAT_Cod = CATALOGO_PRECOS.CAT_Cod
INNER JOIN TIPOS_MIDIAS
	ON CODFILMES.TIP_Cod = TIPOS_MIDIAS.TIP_Cod 
WHERE CODFILMES.COD_Cod = 1;

 

-- CONSULTA CATALOGO DE PRECOS --



-- Consulta dados do Filme --

SELECT CODFILMES.COD_Cod, FILMES.FIL_Titulo, TIPOS_MIDIAS.TIP_Desc, GENEROS.GEN_Desc, CATALOGO_PRECOS.CAT_DESCRICAO, FILMES.FIL_Data_Lanc, FILMES.FIL_Classificacao, FILMES.FIL_Diretor, FILMES.FIL_Produtora, FILMES.FIL_Sinopse 
FROM CODFILMES 
	INNER JOIN FILMES
		ON CODFILMES.FIL_Cod = FILMES.FIL_Cod
	INNER JOIN GENEROS 
		ON FILMES.GEN_Cod = GENEROS.GEN_Cod 
	INNER JOIN CATALOGO_PRECOS 
		ON FILMES.CAT_Cod = CATALOGO_PRECOS.CAT_Cod
	INNER JOIN TIPOS_MIDIAS
	ON CODFILMES.TIP_Cod = TIPOS_MIDIAS.TIP_Cod 
	WHERE CODFILMES.COD_Cod = 1;
	
	

SELECT IDIOMAS.IDI_Desc FROM IDIOMAS INNER JOIN REL_FIL_IDI
ON IDIOMAS.IDI_Cod = REL_FIL_IDI.IDI_Cod
WHERE REL_FIL_IDI.FIL_Cod = 1
ORDER BY IDIOMAS.IDI_Desc;


-- *********************************** --
--    Populando a tabela de locação    --
-- *********************************** --

UPDATE CODFILMES SET CODFILMES.COD_Status = 0 WHERE CODFILMES.COD_Cod = 1;

SELECT * FROM CLIENTES

UPDATE CLIENTES SET CLIENTES.CLI_Saldo = -7.00 WHERE CLIENTES.CLI_Cod = 1;

SELECT * FROM LOCACOES;

SELECT LOCACOES.CLI_Cod, LOCACOES.LOC_Dep FROM LOCACOES WHERE LOCACOES.LOC_Status = 0 AND LOCACOES.COD_Cod = 4;

SP_HELP LOCACOES

select GETDATE();
select DATEDIFF(DAY, LOCACOES.LOC_Data_Dev, GETDATE()) from LOCACOES

select * from CLIENTES



SELECT CODFILMES.COD_Cod, FILMES.FIL_Titulo, LOCACOES.LOC_Data_Loc, LOCACOES.LOC_Data_Dev, CATALOGO_PRECOS.CAT_DESCRICAO, LOCACOES.LOC_Valor, DATEDIFF(DAY, LOCACOES.LOC_Data_Dev, GETDATE()) as ATRASO
FROM CODFILMES
	INNER JOIN FILMES
		ON CODFILMES.FIL_Cod = FILMES.FIL_Cod
	INNER JOIN LOCACOES
		ON CODFILMES.COD_Cod = LOCACOES.COD_Cod
	INNER JOIN CATALOGO_PRECOS
		ON CATALOGO_PRECOS.CAT_Cod = FILMES.CAT_Cod
WHERE LOCACOES.CLI_Cod = 1
		

select * from LOCACOES

UPDATE LOCACOES SET LOC_Data_Dev = '2011-12-04' WHERE LOCACOES.COD_Cod = 1;

SELECT LOCACOES.COD_Cod FROM LOCACOES

SELECT LOC_Data_Loc, LOC_Data_Dev, FIL_Titulo, GEN_Desc, FIL_Classificacao, TIP_Desc, CAT_DESCRICAO, LOC_Valor FROM CODFILMES INNER JOIN FILMES ON CODFILMES.FIL_Cod = FILMES.FIL_Cod INNER JOIN TIPOS_MIDIAS ON TIPOS_MIDIAS.TIP_Cod = CODFILMES.TIP_Cod INNER JOIN GENEROS ON GENEROS.GEN_Cod = FILMES.GEN_Cod INNER JOIN LOCACOES ON CODFILMES.COD_Cod = LOCACOES.COD_Cod INNER JOIN CATALOGO_PRECOS	ON CATALOGO_PRECOS.CAT_Cod = FILMES.CAT_Cod WHERE LOCACOES.CLI_Cod =1

SELECT FIL_Cod FROM FILMES INNER JOIN  CODFILMES ON CODFILMES.FIL_Cod = FILMES.FIL_Cod INNER JOIN LOCACOES ON LOCACOES.COD_Cod = CODFILMES.COD_Cod WHERE LOCACOES.CLI_Cod = 1

SELECT * FROM CIDADES 






SET LANGUAGE BRAZILIAN
SELECT * FROM CLIENTES INNER JOIN ENDERECOS ON ENDERECOS.END_Cod = CLIENTES.END_Cod INNER JOIN CIDADES ON CIDADES.CID_Cod = ENDERECOS.CID_Cod WHERE CLIENTES.CLI_Cod = 5




delete from CIDADES where CID_Cod = 27

select *from CIDADES

SP_HELP CATALOGO_PRECOS

INSERT INTO USUARIO VALUES ('Administrador', '123456789', '12345678911', '01-01-2000', 'M', 'C:\PROGRAMA LOCADORA\BANCO DE DADOS\IMAGENS USUARIO\.JPG', 'ADM', '33354741122871651676713774147412831195') 



SELECT CAT_Cod, CAT_DESCRICAO, VAL_Valor FROM CATALOGO_PRECOS
SELECT VAL_Valor FROM CATALOGO_PRECOS WHERE CAT_DESCRICAO = 'NORMAL';

UPDATE CATALOGO_PRECOS SET VAL_Valor = 3.00 WHERE CAT_DESCRICAO = 'NORMAL';

SELECT FIL_Cod, FIL_Titulo, GENEROS.GEN_Desc, CAT_DESCRICAO FROM FILMES INNER JOIN GENEROS ON GENEROS.GEN_Cod = FILMES.GEN_Cod INNER JOIN CATALOGO_PRECOS ON CATALOGO_PRECOS.CAT_Cod = FILMES.CAT_Cod WHERE FIL_Cod = 1



